apiVersion: v1
kind: Secret
metadata:
  name: tekton-hub-api
type: Opaque
stringData:
  GH_CLIENT_ID: 'b42a3e9a4e5200fef2ff'
  GH_CLIENT_SECRET: '8e4515e6fb5ef69b2e6e6d0451bcdce65d365487'
  GHE_URL: ''
  GL_CLIENT_ID: ''
  GL_CLIENT_SECRET: ''
  GLE_URL: ''
  BB_CLIENT_ID: ''
  BB_CLIENT_SECRET: ''
  GG_CLIENT_ID: '' 
  GG_CLIENT_SECRET: ''
  JWT_SIGNING_KEY: 'random'
  ACCESS_JWT_EXPIRES_IN: '15m'
  REFRESH_JWT_EXPIRES_IN: '10w'
  AUTH_BASE_URL: 'http://localhost:4200'
